# Generated by Django 5.2.14 on 2026-05-31 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('timezone', models.CharField(default='Europe/Kiev', max_length=64)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended')], default='draft', max_length=16)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerBotSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_menu_without_session', models.BooleanField(default=True)),
                ('show_help_button', models.BooleanField(default=True)),
                ('show_session_button', models.BooleanField(default=True)),
                ('show_cart_button', models.BooleanField(default=True)),
                ('show_checkout_button', models.BooleanField(default=True)),
                ('show_loyalty_button', models.BooleanField(default=True)),
                ('guest_order_flow', models.CharField(choices=[('hybrid', 'Hybrid'), ('cart_only', 'Cart only'), ('quick_order_only', 'Quick order only')], default='hybrid', help_text='Controls whether guests use the cart flow, quick order flow, or both.', max_length=32)),
                ('guest_flow_code', models.CharField(blank=True, help_text='Optional named guest flow branch for partner-specific code paths.', max_length=64)),
                ('staff_flow_code', models.CharField(blank=True, help_text='Optional named staff flow branch for partner-specific code paths.', max_length=64)),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Reserved for future feature flags and partner-specific bot behavior.')),
                ('button_menu_label', models.CharField(default='Открыть меню', max_length=64)),
                ('button_session_label', models.CharField(default='Мой стол', max_length=64)),
                ('button_cart_label', models.CharField(default='Корзина', max_length=64)),
                ('button_checkout_label', models.CharField(default='Оформить заказ', max_length=64)),
                ('button_help_label', models.CharField(default='Как заказать', max_length=64)),
                ('button_loyalty_label', models.CharField(default='Бонусы', max_length=64)),
                ('welcome_message_template', models.TextField(blank=True, help_text='Variables: {partner_name}')),
                ('table_activated_message_template', models.TextField(blank=True, help_text='Variables: {partner_name}, {table_number}')),
                ('menu_header_template', models.TextField(blank=True, help_text='Variables: {partner_name}')),
                ('menu_requires_session_hint_template', models.TextField(blank=True, help_text='Shown when menu is visible but ordering still requires QR.')),
                ('menu_active_session_hint_template', models.TextField(blank=True, help_text='Variables: {table_number}')),
                ('menu_empty_message_template', models.TextField(blank=True)),
                ('ordering_help_message_template', models.TextField(blank=True)),
                ('cart_empty_message_template', models.TextField(blank=True)),
                ('cart_cleared_message_template', models.TextField(blank=True)),
                ('order_created_message_template', models.TextField(blank=True, help_text='Variables: {order_public_id}, {total_amount}, {status_display}')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_settings', to='partners.partner')),
            ],
            options={
                'ordering': ['partner__name'],
            },
        ),
        migrations.CreateModel(
            name='BotInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('token_encrypted', models.TextField()),
                ('mode', models.CharField(choices=[('polling', 'Polling'), ('webhook', 'Webhook')], default='polling', max_length=16)),
                ('webhook_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_instances', to='partners.partner')),
            ],
            options={
                'ordering': ['partner__name', 'username'],
                'constraints': [models.UniqueConstraint(fields=('partner', 'username'), name='unique_bot_username_per_partner')],
            },
        ),
    ]
