# Generated by Django 5.2.14 on 2026-06-12 03:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('timezone', models.CharField(default='Europe/Kiev', max_length=64)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended')], default='draft', max_length=16)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerBotSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_loyalty_enabled', models.BooleanField(default=True)),
                ('module_menu_enabled', models.BooleanField(default=True)),
                ('module_tables_enabled', models.BooleanField(default=True)),
                ('module_delivery_enabled', models.BooleanField(default=False)),
                ('module_pickup_enabled', models.BooleanField(default=False)),
                ('module_cart_enabled', models.BooleanField(default=True)),
                ('module_orders_enabled', models.BooleanField(default=True)),
                ('module_billing_enabled', models.BooleanField(default=False)),
                ('module_staff_call_enabled', models.BooleanField(default=False)),
                ('module_quick_sale_enabled', models.BooleanField(default=True)),
                ('module_reports_enabled', models.BooleanField(default=True)),
                ('module_broadcasts_enabled', models.BooleanField(default=False)),
                ('allow_multiple_active_sessions_per_guest', models.BooleanField(default=False)),
                ('auto_close_table_session_after_payment', models.BooleanField(default=True)),
                ('max_menu_items_per_category_message', models.PositiveSmallIntegerField(default=8)),
                ('duplicate_request_cooldown_seconds', models.PositiveSmallIntegerField(default=45)),
                ('allow_menu_without_session', models.BooleanField(default=True)),
                ('staff_call_waiter_enabled', models.BooleanField(default=True)),
                ('staff_call_bartender_enabled', models.BooleanField(default=True)),
                ('staff_call_hookah_enabled', models.BooleanField(default=True)),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Reserved for future feature flags and partner-specific bot behavior.')),
                ('button_menu_label', models.CharField(default='Открыть меню', max_length=64)),
                ('button_session_label', models.CharField(default='Мой стол', max_length=64)),
                ('button_cart_label', models.CharField(default='Корзина', max_length=64)),
                ('button_checkout_label', models.CharField(default='Оформить заказ', max_length=64)),
                ('button_delivery_label', models.CharField(default='Заказать доставку', max_length=64)),
                ('button_pickup_label', models.CharField(default='Самовывоз', max_length=64)),
                ('button_help_label', models.CharField(default='Как заказать', max_length=64)),
                ('button_loyalty_label', models.CharField(default='Бонусы', max_length=64)),
                ('button_call_staff_label', models.CharField(default='Позвать персонал', max_length=64)),
                ('button_request_bill_label', models.CharField(default='Запросить счёт', max_length=64)),
                ('button_call_waiter_label', models.CharField(default='Официант', max_length=64)),
                ('button_call_bartender_label', models.CharField(default='Бар / касса', max_length=64)),
                ('button_call_hookah_label', models.CharField(default='Кальянщик', max_length=64)),
                ('welcome_message_template', models.TextField(blank=True, help_text='Variables: {partner_name}')),
                ('table_activated_message_template', models.TextField(blank=True, help_text='Variables: {partner_name}, {table_number}')),
                ('menu_header_template', models.TextField(blank=True, help_text='Variables: {partner_name}')),
                ('menu_requires_session_hint_template', models.TextField(blank=True, help_text='Shown when menu is visible but ordering still requires QR.')),
                ('menu_active_session_hint_template', models.TextField(blank=True, help_text='Variables: {table_number}')),
                ('menu_empty_message_template', models.TextField(blank=True)),
                ('ordering_help_message_template', models.TextField(blank=True)),
                ('cart_empty_message_template', models.TextField(blank=True)),
                ('cart_cleared_message_template', models.TextField(blank=True)),
                ('staff_call_prompt_template', models.TextField(blank=True, help_text='Shown when the guest opens the staff-call actions.')),
                ('staff_call_success_template', models.TextField(blank=True, help_text='Variables: {partner_name}, {table_number}, {call_target_label}')),
                ('request_bill_prompt_template', models.TextField(blank=True, help_text='Shown when the guest opens billing request options.')),
                ('request_bill_personal_success_template', models.TextField(blank=True, help_text='Variables: {partner_name}, {table_number}, {bill_public_id}')),
                ('request_bill_shared_success_template', models.TextField(blank=True, help_text='Variables: {partner_name}, {table_number}, {bill_public_id}')),
                ('request_bill_custom_success_template', models.TextField(blank=True, help_text='Variables: {partner_name}, {table_number}')),
                ('order_created_message_template', models.TextField(blank=True, help_text='Variables: {order_public_id}, {total_amount}, {status_display}')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_settings', to='partners.partner')),
            ],
            options={
                'ordering': ['partner__name'],
            },
        ),
        migrations.CreateModel(
            name='BotInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('token_encrypted', models.TextField()),
                ('mode', models.CharField(choices=[('polling', 'Polling'), ('webhook', 'Webhook')], default='polling', max_length=16)),
                ('webhook_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_instances', to='partners.partner')),
            ],
            options={
                'ordering': ['partner__name', 'username'],
                'constraints': [models.UniqueConstraint(fields=('partner', 'username'), name='unique_bot_username_per_partner')],
            },
        ),
    ]
