# Generated by Django 5.2.14 on 2026-06-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerbotsettings',
            name='button_call_bartender_label',
            field=models.CharField(default='Бар / касса', max_length=64),
        ),
        migrations.AddField(
            model_name='partnerbotsettings',
            name='button_call_hookah_label',
            field=models.CharField(default='Кальянщик', max_length=64),
        ),
        migrations.AddField(
            model_name='partnerbotsettings',
            name='button_call_staff_label',
            field=models.CharField(default='Позвать персонал', max_length=64),
        ),
        migrations.AddField(
            model_name='partnerbotsettings',
            name='button_call_waiter_label',
            field=models.CharField(default='Официант', max_length=64),
        ),
        migrations.AddField(
            model_name='partnerbotsettings',
            name='show_call_staff_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerbotsettings',
            name='staff_call_bartender_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partnerbotsettings',
            name='staff_call_hookah_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partnerbotsettings',
            name='staff_call_prompt_template',
            field=models.TextField(blank=True, help_text='Shown when the guest opens the staff-call actions.'),
        ),
        migrations.AddField(
            model_name='partnerbotsettings',
            name='staff_call_success_template',
            field=models.TextField(blank=True, help_text='Variables: {partner_name}, {table_number}, {call_target_label}'),
        ),
        migrations.AddField(
            model_name='partnerbotsettings',
            name='staff_call_waiter_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
