# Generated by Django 5.2.15 on 2026-06-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerbotsettings',
            old_name='button_loyalty_label',
            new_name='button_my_profile',
        ),
        migrations.AlterField(
            model_name='partnerbotsettings',
            name='button_my_profile',
            field=models.CharField(default='Мой профиль', max_length=64),
        ),
        migrations.AlterField(
            model_name='partnerbotsettings',
            name='module_billing_enabled',
            field=models.BooleanField(default=False, help_text='Счета, оплаты и списание бонусов. Требует модуль заказов. Запрос счёта гостем доступен только при включённых столах.', verbose_name='Счета и оплаты'),
        ),
        migrations.AlterField(
            model_name='partnerbotsettings',
            name='module_broadcasts_enabled',
            field=models.BooleanField(default=False, help_text='Маркетинговые и информационные сообщения гостям.', verbose_name='Рассылки'),
        ),
        migrations.AlterField(
            model_name='partnerbotsettings',
            name='module_cart_enabled',
            field=models.BooleanField(default=True, help_text='Сбор позиций перед заказом. Требует меню и модуль заказов.', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='partnerbotsettings',
            name='module_delivery_enabled',
            field=models.BooleanField(default=False, help_text='Сценарий заказа на доставку. Включается независимо от столов.', verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='partnerbotsettings',
            name='module_loyalty_enabled',
            field=models.BooleanField(default=True, help_text='Базовый модуль: регистрация гостя, код клиента, бонусный баланс.', verbose_name='Лояльность и профиль клиента'),
        ),
        migrations.AlterField(
            model_name='partnerbotsettings',
            name='module_menu_enabled',
            field=models.BooleanField(default=True, help_text='Категории и позиции. Нужен для заказов и быстрых продаж.', verbose_name='Меню'),
        ),
        migrations.AlterField(
            model_name='partnerbotsettings',
            name='module_orders_enabled',
            field=models.BooleanField(default=True, help_text='Оформление и обработку заказов. Требует меню и хотя бы один сценарий: столы, доставку или самовывоз.', verbose_name='Заказы'),
        ),
        migrations.AlterField(
            model_name='partnerbotsettings',
            name='module_pickup_enabled',
            field=models.BooleanField(default=False, help_text='Сценарий заказа на самовывоз. Включается независимо от столов.', verbose_name='Самовывоз'),
        ),
        migrations.AlterField(
            model_name='partnerbotsettings',
            name='module_quick_sale_enabled',
            field=models.BooleanField(default=True, help_text='Продажа на кассе по коду клиента. Требует меню и лояльность.', verbose_name='Быстрые продажи'),
        ),
        migrations.AlterField(
            model_name='partnerbotsettings',
            name='module_reports_enabled',
            field=models.BooleanField(default=True, help_text='Операционный отчёт в staff-боте.', verbose_name='Отчёт дня'),
        ),
        migrations.AlterField(
            model_name='partnerbotsettings',
            name='module_staff_call_enabled',
            field=models.BooleanField(default=False, help_text='Кнопка вызова официанта/бара/кальянщика. Требует столы.', verbose_name='Вызов персонала'),
        ),
        migrations.AlterField(
            model_name='partnerbotsettings',
            name='module_tables_enabled',
            field=models.BooleanField(default=True, help_text='Сценарий заказа за столом. Нужен для вызова персонала и запроса счёта.', verbose_name='Столы и QR-сессии'),
        ),
    ]
