# Generated by Django 5.2.14 on 2026-06-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partnerbotsettings_button_call_bartender_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerbotsettings',
            name='button_request_bill_label',
            field=models.CharField(default='Запросить счёт', max_length=64),
        ),
        migrations.AddField(
            model_name='partnerbotsettings',
            name='request_bill_custom_success_template',
            field=models.TextField(blank=True, help_text='Variables: {partner_name}, {table_number}'),
        ),
        migrations.AddField(
            model_name='partnerbotsettings',
            name='request_bill_personal_success_template',
            field=models.TextField(blank=True, help_text='Variables: {partner_name}, {table_number}, {bill_public_id}'),
        ),
        migrations.AddField(
            model_name='partnerbotsettings',
            name='request_bill_prompt_template',
            field=models.TextField(blank=True, help_text='Shown when the guest opens billing request options.'),
        ),
        migrations.AddField(
            model_name='partnerbotsettings',
            name='request_bill_shared_success_template',
            field=models.TextField(blank=True, help_text='Variables: {partner_name}, {table_number}, {bill_public_id}'),
        ),
        migrations.AddField(
            model_name='partnerbotsettings',
            name='show_request_bill_button',
            field=models.BooleanField(default=False),
        ),
    ]
