# Generated by Django 5.2.14 on 2026-06-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_assignee_and_accepted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
