# Generated by Django 5.2.14 on 2026-08-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_prepare_orders_and_carts_for_non_table_flows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("terminal", "Terminal"),
                    ("mixed", "Mixed"),
                    ("bonuses", "Bonuses"),
                ],
                default="cash",
                max_length=16,
            ),
        ),
    ]
