# Generated by Django 5.2.14 on 2026-08-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_alter_menuitem_price"),
        ("partners", "0005_partnerbotsettings_button_profile_bonuses_label"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="menuitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gt", 0)), name="menu_item_price_positive"
            ),
        ),
    ]
