# Generated by Django 5.2.14 on 2026-06-12 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('orders', '0001_initial'),
        ('partners', '0001_initial'),
        ('tables', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='primary_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_bills', to='users.guestprofile'),
        ),
        migrations.AddField(
            model_name='bill',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='tables.table'),
        ),
        migrations.AddField(
            model_name='billingrequest',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_requests', to='billing.bill'),
        ),
        migrations.AddField(
            model_name='billingrequest',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_requests', to='users.guestprofile'),
        ),
        migrations.AddField(
            model_name='billingrequest',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='billingrequest',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_requests', to='tables.table'),
        ),
        migrations.AddField(
            model_name='billingrequest',
            name='table_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_requests', to='tables.tablesession'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.bill'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_items', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='billorder',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_orders', to='billing.bill'),
        ),
        migrations.AddField(
            model_name='billorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_links', to='orders.order'),
        ),
        migrations.AddField(
            model_name='billorder',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_receipts', to='billing.bill'),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.bill'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_receipts', to='billing.payment'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('partner', 'public_id'), name='unique_bill_public_id_per_partner'),
        ),
        migrations.AddConstraint(
            model_name='billorder',
            constraint=models.UniqueConstraint(fields=('bill', 'order'), name='unique_order_per_bill'),
        ),
    ]
