# Generated by Django 5.2.14 on 2026-06-01 03:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('partners', '0003_partnerbotsettings_button_request_bill_label_and_more'),
        ('tables', '0002_initial'),
        ('users', '0003_adminaccessprofile_preset'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('personal', 'Personal bill'), ('shared', 'Shared bill'), ('custom_split', 'Custom split')], max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('auto_prepared', 'Auto prepared'), ('processed', 'Processed'), ('canceled', 'Canceled')], default='open', max_length=24)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_requests', to='billing.bill')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_requests', to='users.guestprofile')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='partners.partner')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_requests', to='tables.table')),
                ('table_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_requests', to='tables.tablesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
