# Generated by Django 5.2.14 on 2026-08-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_remove_fiscalreceipt_and_prepare_non_table_bills"),
        ("orders", "0004_alter_order_payment_method"),
        ("partners", "0005_partnerbotsettings_button_profile_bonuses_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("terminal", "Terminal"),
                    ("online", "Online"),
                    ("mixed", "Mixed"),
                    ("bonuses", "Bonuses"),
                ],
                default="cash",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="billitem",
            constraint=models.UniqueConstraint(
                fields=("partner", "order_item"), name="unique_order_item_bill_allocation"
            ),
        ),
    ]
