# Generated by Django 5.2.14 on 2026-05-31 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('accrual', 'Accrual'), ('redemption', 'Redemption'), ('expiration', 'Expiration'), ('manual', 'Manual')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalkInSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_awarded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comment', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('trigger_event', models.CharField(choices=[('visit', 'Visit'), ('order_completed', 'Order completed'), ('manual_purchase', 'Manual purchase')], default='order_completed', max_length=32)),
                ('program_type', models.CharField(choices=[('cashback', 'Cashback'), ('visit', 'Visit'), ('milestone', 'Milestone')], max_length=16)),
                ('strategy_code', models.CharField(blank=True, help_text='Optional custom strategy key for partner-specific bonus code paths.', max_length=64)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('min_order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('milestone_order_count', models.PositiveIntegerField(default=0)),
                ('max_redeem_share', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('expires_in_days', models.PositiveIntegerField(default=90)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Reserved for custom strategy options and partner-specific tuning.')),
                ('is_active', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='partners.partner')),
            ],
            options={
                'ordering': ['partner__name', 'name'],
            },
        ),
    ]
