# Generated by Django 5.2.14 on 2026-06-12 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bonuses', '0001_initial'),
        ('menu', '0001_initial'),
        ('orders', '0001_initial'),
        ('partners', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bonustransaction',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_transactions', to='users.guestprofile'),
        ),
        migrations.AddField(
            model_name='bonustransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_transactions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='bonustransaction',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='bonustransaction',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='bonuses.bonusprogram'),
        ),
        migrations.AddField(
            model_name='walkinsale',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_walk_in_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walkinsale',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walk_in_sales', to='users.guestprofile'),
        ),
        migrations.AddField(
            model_name='walkinsale',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='walkinsaleitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walk_in_sale_items', to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='walkinsaleitem',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='walkinsaleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bonuses.walkinsale'),
        ),
    ]
