# Generated by Django 5.2.15 on 2026-06-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkinsale',
            name='bonus_spent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
