# Generated by Django 5.2.14 on 2026-08-06 05:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_alter_payment_method_and_more"),
        ("bonuses", "0003_walkinsale_bonus_spent"),
        ("orders", "0004_alter_order_payment_method"),
        ("partners", "0005_partnerbotsettings_button_profile_bonuses_label"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonustransaction",
            name="bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bonus_transactions",
                to="billing.bill",
            ),
        ),
        migrations.AddField(
            model_name="bonustransaction",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="bonustransaction",
            name="source_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="bonustransaction",
            name="source_type",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="bonustransaction",
            name="walk_in_sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bonus_transactions",
                to="bonuses.walkinsale",
            ),
        ),
        migrations.AlterField(
            model_name="bonusprogram",
            name="max_redeem_share",
            field=models.DecimalField(
                decimal_places=2,
                default=30,
                help_text="Maximum percentage of a bill payable with bonuses (0-100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="bonustransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("partner", "idempotency_key"),
                name="unique_bonus_idempotency_per_partner",
            ),
        ),
    ]
