# Generated by Django 5.2.14 on 2026-08-06 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bonuses", "0005_alter_walkinsale_amount"),
        ("partners", "0005_partnerbotsettings_button_profile_bonuses_label"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="walkinsale",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="walk_in_sale_amount_positive"
            ),
        ),
    ]
