# Generated by Django 5.2.14 on 2026-08-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0005_partnerbotsettings_button_profile_bonuses_label"),
        ("tables", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tablesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("partner", "guest"),
                name="unique_active_table_session_per_partner_guest",
            ),
        ),
    ]
