# Generated by Django 5.2.14 on 2026-06-01 01:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_partner_owner', models.BooleanField(default=False)),
                ('can_access_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_access_profiles', to='partners.partner')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_access_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['partner__name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='AdminSectionPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('partner_profile', 'Partner profile'), ('bot_instances', 'Bot instances'), ('bot_content', 'Bot content'), ('tables', 'Tables'), ('menu', 'Menu'), ('orders', 'Orders'), ('bonuses', 'Bonuses'), ('employees', 'Employees'), ('admin_access', 'Admin access'), ('notifications', 'Notifications'), ('analytics', 'Analytics'), ('billing', 'Billing')], max_length=32)),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_change', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_manage_sensitive', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_permissions', to='users.adminaccessprofile')),
            ],
            options={
                'ordering': ['section'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'section'), name='unique_admin_section_permission_per_profile')],
            },
        ),
    ]
