# Generated by Django 5.2.14 on 2026-06-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adminaccessprofile_adminsectionpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccessprofile',
            name='preset',
            field=models.CharField(choices=[('custom', 'Custom'), ('owner', 'Owner'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('content_manager', 'Content manager')], default='custom', max_length=32),
        ),
    ]
