# Generated by Django 5.2.14 on 2026-06-12 03:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerDailyMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket_date', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('average_check', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active_guests', models.PositiveIntegerField(default=0)),
                ('repeat_visits', models.PositiveIntegerField(default=0)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='partners.partner')),
            ],
            options={
                'ordering': ['-bucket_date'],
                'constraints': [models.UniqueConstraint(fields=('partner', 'bucket_date'), name='unique_partner_metric_per_day')],
            },
        ),
    ]
