# Generated by Django 5.2.14 on 2026-06-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='bot_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='notify_on_order_created',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='notify_on_order_status_changed',
            field=models.BooleanField(default=True),
        ),
    ]
