# Generated by Django 5.2.14 on 2026-06-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeeprofile_bot_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='notify_on_guest_calls',
            field=models.BooleanField(default=True),
        ),
    ]
