# Generated by Django 5.2.14 on 2026-06-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeeprofile_notify_on_guest_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='notify_on_billing_requests',
            field=models.BooleanField(default=True),
        ),
    ]
