# Generated by Django 5.2.14 on 2026-06-12 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('notifications', '0001_initial'),
        ('orders', '0001_initial'),
        ('partners', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='guest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='users.guestprofile'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='staffnotification',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_notifications', to='employees.employeeprofile'),
        ),
        migrations.AddField(
            model_name='staffnotification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_notifications', to='orders.order'),
        ),
        migrations.AddField(
            model_name='staffnotification',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='partners.partner'),
        ),
    ]
