# Generated by Django 5.2.14 on 2026-06-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastcampaign',
            name='delivered_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broadcastcampaign',
            name='delivery_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broadcastcampaign',
            name='failed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broadcastcampaign',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffnotification',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffnotification',
            name='delivery_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffnotification',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='broadcastcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=16),
        ),
    ]
