# Generated by Django 5.2.14 on 2026-06-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_broadcastcampaign_delivered_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffnotification',
            name='category',
            field=models.CharField(choices=[('order_created', 'Order created'), ('order_status_changed', 'Order status changed'), ('guest_call', 'Guest call')], max_length=32),
        ),
    ]
