# Generated by Django 5.2.14 on 2026-06-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_staffnotification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffnotification',
            name='category',
            field=models.CharField(choices=[('order_created', 'Order created'), ('order_status_changed', 'Order status changed'), ('guest_call', 'Guest call'), ('billing_request', 'Billing request')], max_length=32),
        ),
    ]
